Repository Alikhll/golang-developer-roadmap, pull requests merged in 2019-04, with the labels that each got.

#2 GLog removed
  ReadMe.md
  golang-developer-roadmap.png
  golang-developer-roadmap.xml
Labels: bug, enhancement

#4 fixed Authentication
  ReadMe.md
Labels: bug

#6 Adding info about CLI development
  ReadMe.md
  golang-developer-roadmap.png
  golang-developer-roadmap.xml
Labels: enhancement

#7 Update Readme to fix type in gRPC-Gateway
  ReadMe.md
Labels: bug

#14 #13 add the rpcx framework in MicroServices/Frameworks
  ReadMe.md
  golang-developer-roadmap.png
  golang-developer-roadmap.xml
Labels: enhancement

#15 Update rpcx in Framework node in zh-CN translation
  i18n/ReadMe-zh-CN.md
  i18n/golang-developer-roadmap-zh-CN.png
  i18n/golang-developer-roadmap-zh-CN.xml
Labels: enhancement

#17 add graphql libraries and fix #10
  ReadMe.md
  golang-developer-roadmap.png
  golang-developer-roadmap.xml
Labels: enhancement

#18 Update message broker links
  ReadMe.md
Labels: bug

#19 Update 'Dep&Graphql&some links' in zh-CN translation
  i18n/ReadMe-zh-CN.md
  i18n/golang-developer-roadmap-zh-CN.png
  i18n/golang-developer-roadmap-zh-CN.xml
Labels: enhancement
